add command not found

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -e;
+#set -e;
 
 HOME=/home/git/.riakcs
 
@@ -90,6 +90,10 @@ case "$1" in
     ;;
   riakcs:list)
     perl ~/s3-curl/s3curl.pl --id admin -- -s -x localhost:${RIAK_PORT} -H "Accept: application/json" http://s3.amazonaws.com/riak-cs/users
+    ;;
+  *)
+    echo "Command Not Found"
+    exit 1
     ;;
 esac
 cat
